### ISSUE TITLE
Dll dosyası eksik

### ISSUE THREAD

**Issue by Adilx05** [buracc/SimpleCL#4]
Network'ün içindeki gatewayin sonunda şöyle bir satır var ;

`            new Injector(SilkroadClient.Launch(), @"C:\Users\burak\Desktop\fuck_burak\Release\fuck_burak.dll").Inject();
`

Bu dll bizde olmadığı için Clientle açmaya çalıştığımızda inject edecek bir dll bulamıyor.

**Comment by buracc** [comment]
Ekledim. Debug/bin dosyasina kopyala
