### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by andrefmandrade** [buracc/SimpleCL#7]
Hey, I'm a long-time silkroad player and I was always fascinated with the botting world of it, but never had a chance to get into it.
Is there any documentation on how to run this project? I'd like to understand how it works and learn about it.

**Comment by buracc** [comment]
I have not written documentation for this project. To run the application, you have to extract the client cache (pk2) first using the pk2extractor project. After that you'll be able to run the SimpleCL project
